name: "hello world workflow"

# Controls when the action will run. Triggers the workflow on push sone to master or production branch.
on:
  push:
    branches:
      - master
      - production

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: "print hello-world"
        run: echo "hello-world"
