name: "Multi event pipeline/ workflow" #Name of the pipeline
on:
    push: # Event: whenever a push is made to the repository on the master branch
        branches:
            - master
    pull_request: # Event: Whenever a pull request is made to the repository
        branches:
            - master

jobs:
    on-push: # Job name
        runs-on: ubuntu-latest
        steps: # steps to be executed in the job
            - name: "Running on master push" # step 1
              run: echo "Running on master push"
    on-pull-request: # Job name
        runs-on: ubuntu-latest
        steps: # steps to be executed in the job
            - name: "Running on pull request"
              run: echo "Running on pull request"
              
