name: "Multi event pipeline/ workflow" #Name of the pipeline
on:
    push: # whenever a push is made to the repository on the master branch
        branches:
            - master
jobs:
    on-push: # Job name
        runs-on: ubuntu-latest
        steps: # steps to be executed in the job
            - name: "Running on master push" # step 1
              run: echo "Running on master push"
